### ISSUE TITLE
Does not work on Firefox

### ISSUE THREAD

**Issue by marquesgabriel** [MaikeMota/comando-voz#1]
It is using a webkit speech recognition

**Comment by marquesgabriel** [comment]
UPDATE:
SpeechRecognition is available on MDN but it's not compatible with any other browser than Chrome.
FF started a project for speech recognition tough. Its called common voice ([https://voice.mozilla.org/en](https://voice.mozilla.org/en))
I suspect it will be available soon. You could put this issue as an future implementation possibility

**Comment by MaikeMota** [comment]
Unfortunately, other browsers seems not implemented this feature, so, for now, only Google Chrome can run this little demo.

Maybe in the future, other browser vendors implement this feature and we can update this demo to run in other browsers.
